In [3]:
import numpy as np

In [7]:
ceros = np.zeros(10)
len(ceros)

10

In [10]:
ceros[5] = 1
ceros

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [19]:
cincuenta = np.arange(1,51)
cincuenta = cincuenta[::-1]
cincuenta

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [23]:
mat = np.arange(9).reshape([3,3])
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
arreglo = [1,2,0,0,4,0]
indexes = []
index = 0

for element in arreglo:
    if(element != 0):
        indexes.append(index)
    index = index + 1

indexes

[0, 1, 4]

In [28]:
indentidad = np.identity(3)
indentidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
rand = np.random.randint(0,100, [3,3,3])
rand

array([[[42, 86, 31],
        [32, 94, 92],
        [61, 80, 55]],

       [[68, 21, 43],
        [28, 81, 31],
        [61, 15, 88]],

       [[15, 12,  0],
        [74, 96, 92],
        [69, 90, 90]]])

In [44]:
maxmin = np.random.randint(0,100,[10,10])
print(maxmin)
print(np.max(maxmin))
print(np.min(maxmin))

[[39 23  0 73  0  0 98 62 68 89]
 [79 78 34 99 93 20 78 39 32 36]
 [73 56  7 15 17 96 20 23  2 69]
 [13  8 87  0 21 83 12  7 72 74]
 [29 77 78 15 57 37 97 85 70 75]
 [58 42 92 43 85  8 68 48 58  9]
 [46  4 59 24 68 46  9 10 34 90]
 [26 67 75 82 82 48 50 65 68 36]
 [36  2 12 51 88 57 68 26 88 65]
 [12 38 51 42 81  6 67 69 30 67]]
99
0


In [79]:
imagen = np.zeros([144,144,3])
imagen[0][1] = [1,2,3]
pixeles = np.concatenate(imagen)
# imagen
np.unique(pixeles, axis=0, return_index=True)
# uni

(array([[0., 0., 0.],
        [1., 2., 3.]]),
 array([0, 1], dtype=int64))

In [86]:
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
# print(pd.Series(mylist))
# print(pd.Series(myarr))
# print(pd.Series(mydict))

In [98]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# ser
df1 = pd.DataFrame()
df1['nums'] = ser
df1.reset_index()

index  nums
0      a     0
1      b     1
2      c     2
3      e     3
4      d     4
5      f     5
6      g     6
7      h     7
8      i     8
9      j     9
10     k    10
11     l    11
12     m    12
13     n    13
14     o    14
15     p    15
16     q    16
17     r    17
18     s    18
19     t    19
20     u    20
21     v    21
22     w    22
23     x    23
24     y    24
25     z    25

In [100]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df = pd.DataFrame()
df['num'] = ser2
df['let'] = ser1
df

num let
0     0   a
1     1   b
2     2   c
3     3   e
4     4   d
5     5   f
6     6   g
7     7   h
8     8   i
9     9   j
10   10   k
11   11   l
12   12   m
13   13   n
14   14   o
15   15   p
16   16   q
17   17   r
18   18   s
19   19   t
20   20   u
21   21   v
22   22   w
23   23   x
24   24   y
25   25   z

In [109]:
# 14