In [2]:
import numpy as np

print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.zeros([1000,200])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
np.ones((7,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [33]:
np.arange(5,19)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [36]:
np.arange(-15,20,2)

array([-15, -13, -11,  -9,  -7,  -5,  -3,  -1,   1,   3,   5,   7,   9,
        11,  13,  15,  17,  19])

In [38]:
np.arange(0,2,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [40]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
np.zeros(20).reshape(4,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
len(np.ones(12))

12

In [48]:
np.zeros(45).reshape(9,5).shape #numero de dimensiones

(9, 5)

In [49]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
np.arange(20).reshape(4,5)[2][3]

13

In [54]:
np.arange(20).reshape(4,5)[2,3]

13

In [56]:
a = np.array([4,5,6])
b = np.array([6,5,4])
a + b

array([10, 10, 10])

In [57]:
a = np.array([4,5,6])
b = np.array([6,5,4])
a - b

array([-2,  0,  2])

In [58]:
a + 7

array([11, 12, 13])

In [59]:
a - 5

array([-1,  0,  1])

In [60]:
a * 5

array([20, 25, 30])

In [63]:
a / 2

array([2. , 2.5, 3. ])

In [67]:
a % b

array([4, 0, 2], dtype=int32)

In [68]:
a % 2

array([0, 1, 0], dtype=int32)

In [77]:
muestra = np.arange(20).reshape(5,2,2)
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [73]:
respuesta = ((muestra % 3) == 0)
respuesta

array([[[ True, False],
        [False,  True],
        [False, False],
        [ True, False],
        [False,  True]],

       [[False, False],
        [ True, False],
        [False,  True],
        [False, False],
        [ True, False]]])

In [74]:
muestra[respuesta]

array([ 0,  3,  6,  9, 12, 15, 18])

In [79]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [96]:
respuesta_2 = muestra > 5
respuesta_3 = muestra < 14
respuesta_4 = muestra % 2 == 0

In [99]:
respuesta = respuesta_2 & respuesta_3 & respuesta_4

In [98]:
respuesta

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True, False]],

       [[ True, False],
        [ True, False]],

       [[ True, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [102]:
respuesta_total = (muestra > 5) & (muestra < 14) & (muestra % 2 == 0)
muestra[respuesta_total]

array([ 6,  8, 10, 12])

In [104]:
A = np.arange(4).reshape([2,2])
A

array([[0, 1],
       [2, 3]])

In [109]:
B = np.arange(4,8).reshape([2,2])
B

array([[4, 5],
       [6, 7]])

In [111]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [113]:
np.dot(B,A)

array([[10, 19],
       [14, 27]])

In [116]:
C = np.arange(12)
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [119]:
C.sum()

66

In [120]:
C.min()

0

In [121]:
C.max()

11

In [123]:
C[5:].min()

5

In [124]:
C.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [125]:
C.reshape(3,2,2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [127]:
C.reshape(3,2,2).sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [128]:
C.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])