In [3]:
import numpy as np

In [4]:
arr = np.arange(11) ** 2
arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [11]:
arr[1:3] #los arreglos de np funcionan igual a los de py

array([1, 4], dtype=int32)

In [13]:
arr[-8:8]

array([ 9, 16, 25, 36, 49], dtype=int32)

In [14]:
arr[-8:-2]

array([ 9, 16, 25, 36, 49, 64], dtype=int32)

In [16]:
arr[8:]

array([ 64,  81, 100], dtype=int32)

In [17]:
arr[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [ ]:
#Cosas nuevas:

In [20]:
arr[0:7:2] #Saltos (en este caso de 2 en 2)

array([ 0,  4, 16, 36], dtype=int32)

In [21]:
arr[::2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [6]:
arr[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [9]:
print(np.arange(10).reshape([2,-1]))
print(np.arange(10).reshape([2,-1])[::-1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]
 [0 1 2 3 4]]
